# docker compose up -d  

version: '3.1'
services:
  nginx:
    restart: always
    image: nginx
    container_name: nginx
    ports: 
      - 1122:1122
      - 2233:2233
    volumes: 
      - ./config/nginx.conf:/etc/nginx/nginx.conf
      - ./build:/usr/share/nginx/html/main
      - ./react-app-qiankun-sub/build:/usr/share/nginx/html/sub